package com.callx.app.activities;

import android.graphics.Color;
import android.graphics.Typeface;
import android.os.Bundle;
import android.view.Gravity;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.LinearLayout;
import android.widget.ProgressBar;
import android.widget.ScrollView;
import android.widget.TextView;
import android.widget.Toast;

import androidx.annotation.Nullable;
import androidx.appcompat.app.AppCompatActivity;

import com.callx.app.perf.PerformanceMonitor;

import java.util.ArrayList;
import java.util.List;

/**
 * PerformanceReportActivity — Chat List → 3-dot menu → "⚡ Performance".
 *
 * Shows REAL numbers measured on this device during this app session:
 *   - Chat List screen load time (Room-first + Firebase-sync path)
 *   - Row bind cost (ChatListAdapter.onBindViewHolder, every bind, not a sample)
 *   - Scroll/UI frame jank (real android.view.FrameMetrics while Chats tab
 *     was on screen — API 24+ only; older devices show "unavailable")
 *   - Live memory snapshot
 *   - A fresh, timed Room query benchmark run the moment this screen opens
 *
 * Nothing here is simulated. If a section shows "no data yet", it means the
 * corresponding activity (scrolling, a cold load) genuinely hasn't happened
 * yet this session — that's true information, not a placeholder to hide.
 *
 * The Weaknesses section is generated by comparing the measured numbers
 * against fixed budgets (60fps frame budget, WhatsApp/Telegram-class bind
 * and query targets already used elsewhere in this codebase's own perf
 * comments) — not a hardcoded message.
 */
public class PerformanceReportActivity extends AppCompatActivity {

    // Budgets — same class of targets already referenced elsewhere in this
    // codebase's own perf work (see MessagePagingAdapter's "P99 < 8ms" bind
    // target and the CI jank baseline's 60fps frame budget).
    private static final long LOAD_GOOD_MS = 150, LOAD_OK_MS = 400;
    private static final double JANK_GOOD_PCT = 2.0, JANK_OK_PCT = 5.0;
    private static final long BIND_GOOD_US = 2000, BIND_OK_US = 8000; // 2ms / 8ms
    private static final long DB_GOOD_MS = 20, DB_OK_MS = 80;
    private static final int MEM_GOOD_PCT = 60, MEM_OK_PCT = 80;

    private LinearLayout root;
    private TextView tvDbResult;
    private ProgressBar dbProgress;

    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        ScrollView scroll = new ScrollView(this);
        scroll.setLayoutParams(new ViewGroup.LayoutParams(
                ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT));

        LinearLayout outer = new LinearLayout(this);
        outer.setOrientation(LinearLayout.VERTICAL);
        outer.setLayoutParams(new ViewGroup.LayoutParams(
                ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.WRAP_CONTENT));

        // Plain code-built header (no Toolbar drawable dependency, same
        // build-safe approach CrashReportActivity uses) — title + close.
        LinearLayout header = new LinearLayout(this);
        header.setOrientation(LinearLayout.HORIZONTAL);
        header.setGravity(Gravity.CENTER_VERTICAL);
        header.setBackgroundColor(Color.parseColor("#1F1F1F"));
        int hPad = dp(16);
        header.setPadding(hPad, hPad, hPad, hPad);

        TextView title = new TextView(this);
        title.setText("⚡ Chat List Performance");
        title.setTextColor(Color.WHITE);
        title.setTextSize(18);
        title.setTypeface(null, Typeface.BOLD);
        header.addView(title, new LinearLayout.LayoutParams(0, ViewGroup.LayoutParams.WRAP_CONTENT, 1f));

        TextView close = new TextView(this);
        close.setText("✕");
        close.setTextColor(Color.WHITE);
        close.setTextSize(20);
        close.setPadding(dp(12), 0, dp(4), 0);
        close.setOnClickListener(v -> finish());
        header.addView(close);

        outer.addView(header, new LinearLayout.LayoutParams(
                ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.WRAP_CONTENT));

        root = new LinearLayout(this);
        root.setOrientation(LinearLayout.VERTICAL);
        int pad = dp(16);
        root.setPadding(pad, pad, pad, pad);
        outer.addView(root);

        scroll.addView(outer);
        setContentView(scroll);

        renderReport();

        Button ultraBtn = new Button(this);
        ultraBtn.setText("🔬 Open Ultra Advanced Diagnostics");
        ultraBtn.setOnClickListener(v ->
                startActivity(new android.content.Intent(this, UltraDiagnosticsActivity.class)));
        LinearLayout.LayoutParams ulp = new LinearLayout.LayoutParams(
                ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.WRAP_CONTENT);
        int uPad = dp(16);
        ulp.leftMargin = uPad;
        ulp.rightMargin = uPad;
        ulp.topMargin = dp(4);
        ulp.bottomMargin = dp(20);
        outer.addView(ultraBtn, ulp);
    }

    @Override
    protected void onResume() {
        super.onResume();
        // Re-render every time the screen is shown so numbers reflect the
        // latest scrolling/usage that happened before opening this report.
        if (root != null && root.getChildCount() > 0) renderReport();
    }

    private void renderReport() {
        root.removeAllViews();

        PerformanceMonitor pm = PerformanceMonitor.get();

        addSectionHeader("📥 Screen Load Time");
        PerformanceMonitor.Stat load = pm.getLoadTimeStatsMs();
        if (load.count == 0) {
            addInfoLine("No load measured yet this session — reopen the Chats tab from a cold app start to capture one.");
        } else {
            addMetricLine("Last-session average", load.avg + " ms", rate(load.avg, LOAD_GOOD_MS, LOAD_OK_MS));
            addMetricLine("Best / Worst", load.p50 + " ms / " + load.max + " ms", null);
            addInfoLine("Measured: fragment start → first real chat row actually rendered (Room-cache-first path).");
        }

        addSectionHeader("🖱️ Scroll Smoothness (Frame Jank)");
        if (!pm.isFrameTrackingSupported()) {
            addInfoLine("Frame-level tracking needs Android 7.0+ (API 24). Not available on this device.");
        } else if (pm.getTotalFrames() == 0) {
            addInfoLine("No frames captured yet — open the Chats tab and scroll the list, then come back to this report.");
        } else {
            long total = pm.getTotalFrames();
            long janky = pm.getJankyFrames();
            double pct = total == 0 ? 0 : (100.0 * janky / total);
            PerformanceMonitor.Stat fd = pm.getFrameDurationStatsMs();
            addMetricLine("Frames captured", String.valueOf(total), null);
            addMetricLine("Janky frames", janky + " (" + String.format(java.util.Locale.US, "%.1f", pct) + "%)",
                    rate((long) (pct * 10), (long) (JANK_GOOD_PCT * 10), (long) (JANK_OK_PCT * 10)));
            addMetricLine("Frame time avg / p90 / p99", fd.avg + " / " + fd.p90 + " / " + fd.p99 + " ms",
                    rate(fd.p99, (long) (1000 / pm.getRefreshRateHz()), (long) (1000 / pm.getRefreshRateHz()) + 6));
            addInfoLine("Display refresh rate: " + Math.round(pm.getRefreshRateHz()) + "Hz → frame budget "
                    + String.format(java.util.Locale.US, "%.1f", 1000.0 / pm.getRefreshRateHz()) + " ms.");
        }

        addSectionHeader("🧱 Row Bind Cost (per chat row)");
        PerformanceMonitor.Stat bind = pm.getBindTimeStatsUs();
        if (bind.count == 0) {
            addInfoLine("No rows bound yet — open the Chats tab first.");
        } else {
            addMetricLine("Rows measured", String.valueOf(bind.count), null);
            addMetricLine("Avg / p50", fmtUs(bind.avg) + " / " + fmtUs(bind.p50), null);
            addMetricLine("p90 / p99", fmtUs(bind.p90) + " / " + fmtUs(bind.p99),
                    rate(bind.p99, BIND_GOOD_US, BIND_OK_US));
            addMetricLine("Worst single bind", fmtUs(bind.max), null);
        }

        addSectionHeader("💾 Database Query Cost");
        tvDbResult = addMetricLine("Chat list query (live)", "measuring…", null);
        dbProgress = new ProgressBar(this);
        root.addView(dbProgress);
        pm.benchmarkChatListQuery(this, (queryMs, rowCount) -> {
            dbProgress.setVisibility(View.GONE);
            if (queryMs < 0) {
                tvDbResult.setText("Chat list query (live): failed to run");
                return;
            }
            tvDbResult.setText("Chat list query (live): " + queryMs + " ms for " + rowCount + " rows");
            tvDbResult.setTextColor(colorFor(rate(queryMs, DB_GOOD_MS, DB_OK_MS)));
            renderWeaknesses(pm, queryMs, rowCount);
        });

        addSectionHeader("📊 Memory (live snapshot)");
        PerformanceMonitor.MemorySnapshot mem = pm.getMemorySnapshot();
        addMetricLine("Heap used", mem.usedMb + " MB / " + mem.maxMb + " MB (" + mem.usedPct() + "%)",
                rate(mem.usedPct(), MEM_GOOD_PCT, MEM_OK_PCT));
        if (mem.nativeMb >= 0) addMetricLine("Native heap", mem.nativeMb + " MB", null);

        addSectionHeader("⚠️ Weaknesses & Suggestions");
        addInfoLine("Calculating (waiting for the live DB query above)…");

        Button reset = new Button(this);
        reset.setText("Reset & Re-measure");
        reset.setOnClickListener(v -> {
            pm.reset();
            Toast.makeText(this, "Counters reset — use the Chats tab for a bit, then reopen this report.", Toast.LENGTH_LONG).show();
            renderReport();
        });
        LinearLayout.LayoutParams rlp = new LinearLayout.LayoutParams(
                ViewGroup.LayoutParams.WRAP_CONTENT, ViewGroup.LayoutParams.WRAP_CONTENT);
        rlp.topMargin = dp(24);
        rlp.bottomMargin = dp(24);
        root.addView(reset, rlp);
    }

    /** Rebuilds the Weaknesses section once the live DB benchmark result is in. */
    private void renderWeaknesses(PerformanceMonitor pm, long dbQueryMs, int rowCount) {
        // Find and clear the existing weaknesses section (last header + its
        // one placeholder line + the button) — rebuild in place.
        int headerIdx = -1;
        for (int i = 0; i < root.getChildCount(); i++) {
            View c = root.getChildAt(i);
            if (c instanceof TextView && "⚠️ Weaknesses & Suggestions".equals(((TextView) c).getText().toString())) {
                headerIdx = i;
                break;
            }
        }
        if (headerIdx == -1) return;
        // Remove everything from the placeholder line through the button.
        while (root.getChildCount() > headerIdx + 1) root.removeViewAt(headerIdx + 1);

        List<String> weaknesses = new ArrayList<>();

        PerformanceMonitor.Stat load = pm.getLoadTimeStatsMs();
        if (load.count > 0 && load.avg >= LOAD_OK_MS)
            weaknesses.add("Chat list takes " + load.avg + "ms to show data — target under " + LOAD_GOOD_MS + "ms. Check whether Room-cache-first path (loadFromRoom) is actually returning fast, or the screen is waiting on Firebase.");
        else if (load.count > 0 && load.avg >= LOAD_GOOD_MS)
            weaknesses.add("Chat list load (" + load.avg + "ms) is okay but not yet best-in-class (<" + LOAD_GOOD_MS + "ms).");

        if (pm.isFrameTrackingSupported() && pm.getTotalFrames() > 0) {
            double pct = 100.0 * pm.getJankyFrames() / pm.getTotalFrames();
            if (pct >= JANK_OK_PCT)
                weaknesses.add(String.format(java.util.Locale.US, "%.1f%% of frames missed the frame budget while scrolling — visible stutter. Check RecycledViewPool sizing and per-row Glide loads.", pct));
            else if (pct >= JANK_GOOD_PCT)
                weaknesses.add(String.format(java.util.Locale.US, "%.1f%% janky frames — usable but not perfectly smooth.", pct));
        }

        PerformanceMonitor.Stat bind = pm.getBindTimeStatsUs();
        if (bind.count > 0 && bind.p99 >= BIND_OK_US)
            weaknesses.add("Row bind p99 is " + fmtUs(bind.p99) + " (worst rows) — over the 8ms budget. Something in onBindViewHolder is doing synchronous work (allocation, bitmap decode, or DB/Firebase call) for a subset of rows.");
        else if (bind.count > 0 && bind.p99 >= BIND_GOOD_US)
            weaknesses.add("Row bind p99 is " + fmtUs(bind.p99) + " — acceptable, room to reach the <2ms target.");

        if (dbQueryMs >= DB_OK_MS)
            weaknesses.add("Chat list DB query took " + dbQueryMs + "ms for " + rowCount + " rows — slow for a local Room read. Check for a missing index on chats(lastMessageAt) or archived.");
        else if (dbQueryMs >= DB_GOOD_MS)
            weaknesses.add("Chat list DB query took " + dbQueryMs + "ms for " + rowCount + " rows — fine, but an index on the sort column could bring this under " + DB_GOOD_MS + "ms.");

        PerformanceMonitor.MemorySnapshot mem = pm.getMemorySnapshot();
        if (mem.usedPct() >= MEM_OK_PCT)
            weaknesses.add("Heap usage is at " + mem.usedPct() + "% of max — close to pressure. Watch for bitmap/cache growth while this tab is open long.");

        if (weaknesses.isEmpty()) {
            addInfoLine("No weaknesses detected against WhatsApp/Telegram-class budgets — this screen is measuring within target on this device right now.");
        } else {
            for (String w : weaknesses) addBullet(w);
        }

        Button reset = new Button(this);
        reset.setText("Reset & Re-measure");
        reset.setOnClickListener(v -> {
            pm.reset();
            Toast.makeText(this, "Counters reset — use the Chats tab for a bit, then reopen this report.", Toast.LENGTH_LONG).show();
            renderReport();
        });
        LinearLayout.LayoutParams rlp = new LinearLayout.LayoutParams(
                ViewGroup.LayoutParams.WRAP_CONTENT, ViewGroup.LayoutParams.WRAP_CONTENT);
        rlp.topMargin = dp(24);
        rlp.bottomMargin = dp(24);
        root.addView(reset, rlp);
    }

    // ── small render helpers ─────────────────────────────────────────────

    /** -1 = good, 0 = ok, 1 = bad */
    private int rate(long value, long goodMax, long okMax) {
        if (value <= goodMax) return -1;
        if (value <= okMax) return 0;
        return 1;
    }

    private int colorFor(int rating) {
        if (rating < 0) return Color.parseColor("#2E7D32");   // green
        if (rating == 0) return Color.parseColor("#F9A825");  // amber
        return Color.parseColor("#C62828");                   // red
    }

    private void addSectionHeader(String text) {
        TextView tv = new TextView(this);
        tv.setText(text);
        tv.setTextSize(16);
        tv.setTypeface(null, Typeface.BOLD);
        tv.setTextColor(Color.parseColor("#212121"));
        LinearLayout.LayoutParams lp = new LinearLayout.LayoutParams(
                ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.WRAP_CONTENT);
        lp.topMargin = dp(20);
        lp.bottomMargin = dp(6);
        root.addView(tv, lp);
    }

    private TextView addMetricLine(String label, String value, @Nullable Integer rating) {
        LinearLayout row = new LinearLayout(this);
        row.setOrientation(LinearLayout.HORIZONTAL);
        row.setGravity(Gravity.CENTER_VERTICAL);

        TextView tvLabel = new TextView(this);
        tvLabel.setText(label);
        tvLabel.setTextSize(14);
        tvLabel.setTextColor(Color.parseColor("#616161"));
        LinearLayout.LayoutParams llp = new LinearLayout.LayoutParams(0, ViewGroup.LayoutParams.WRAP_CONTENT, 1f);
        row.addView(tvLabel, llp);

        TextView tvValue = new TextView(this);
        tvValue.setText(value);
        tvValue.setTextSize(14);
        tvValue.setTypeface(null, Typeface.BOLD);
        tvValue.setTextColor(rating == null ? Color.parseColor("#212121") : colorFor(rating));
        row.addView(tvValue);

        LinearLayout.LayoutParams rlp = new LinearLayout.LayoutParams(
                ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.WRAP_CONTENT);
        rlp.topMargin = dp(4);
        root.addView(row, rlp);
        return tvValue;
    }

    private void addInfoLine(String text) {
        TextView tv = new TextView(this);
        tv.setText(text);
        tv.setTextSize(12);
        tv.setTextColor(Color.parseColor("#9E9E9E"));
        LinearLayout.LayoutParams lp = new LinearLayout.LayoutParams(
                ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.WRAP_CONTENT);
        lp.topMargin = dp(2);
        root.addView(tv, lp);
    }

    private void addBullet(String text) {
        TextView tv = new TextView(this);
        tv.setText("• " + text);
        tv.setTextSize(13);
        tv.setTextColor(Color.parseColor("#B71C1C"));
        tv.setLineSpacing(dp(2), 1f);
        LinearLayout.LayoutParams lp = new LinearLayout.LayoutParams(
                ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.WRAP_CONTENT);
        lp.topMargin = dp(8);
        root.addView(tv, lp);
    }

    private String fmtUs(long micros) {
        if (micros < 1000) return micros + "µs";
        return String.format(java.util.Locale.US, "%.1fms", micros / 1000.0);
    }

    private int dp(int v) {
        return (int) (v * getResources().getDisplayMetrics().density);
    }
}
