services:
  - type: web
    name: callx-server
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: FIREBASE_SERVICE_ACCOUNT
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        value: dvqqgqdls
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: DB_URL
        value: https://sathix-97a76-default-rtdb.asia-southeast1.firebasedatabase.app
