services:
  - type: web
    name: callx-server
    runtime: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: FIREBASE_SERVICE_ACCOUNT
        sync: false
      - key: DB_URL
        value: "https://sathix-97a76-default-rtdb.asia-southeast1.firebasedatabase.app"
      - key: CLOUDINARY_CLOUD_NAME
        value: "dvqqgqdls"
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: TURN_SECRET
        sync: false
      - key: TURN_HOST
        sync: false
      - key: TURN_PORT
        value: "3478"
    healthCheckPath: /healthz
    autoDeploy: true
